# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='target',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='data',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
