# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0002_auto_20160411_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='features',
            field=models.TextField(default='[]'),
        ),
    ]
